/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.1-7-g3728de467d-20260521"
#endif /* AVUTIL_FFVERSION_H */
